cmake: set CMAKE_CXX_LINK_FLAGS in CheckAtomic module
The checks are valid, the "atomic" is added to CMAKE_REQUIRED_LIBRARIES,
but it fails during linking with undefined reference to __atomic_store_8
error.

"-latomic" needs to be added to CMAKE_CXX_LINK_FLAGS to fix that.